FROM alpine

MAINTAINER Virgil Chereches <virgil.chereches@gmx.net>


RUN apk add --update curl && \
    rm -rf /var/cache/apk/*

RUN cd /tmp && \
    curl -Lko heka.tar.gz https://github.com/mozilla-services/heka/releases/download/v0.10.0/heka-0_10_0-linux-amd64.tar.gz && \
    tar xzvf heka.tar.gz && \
    mkdir -p /opt/heka && \
    mv heka*/* /opt/heka/ && \
    rm -f heka.tar.gz && mkdir /opt/heka/etc && rmdir heka*

COPY *.toml /opt/heka/etc/

VOLUME /var/run/docker.sock

WORKDIR /opt/heka


ENTRYPOINT ["/opt/heka/bin/hekad", "-c", "/opt/heka/etc"]
