FROM alpine:3.2

MAINTAINER Virgil Chereches <virgil.chereches@gmx.net>

ENV HEKA_VERSION v0.10.0
ENV GOPATH /go

RUN apk add --update build-base curl go git mercurial ca-certificates cmake perl && \
    mkdir -p ${GOPATH}/src/github.com/mozilla-services/ && \
    cd ${GOPATH}/src/github.com/mozilla-services/ && \
    git clone https://github.com/mozilla-services/heka.git -b ${HEKA_VERSION} && \
    cd ${GOPATH}/src/github.com/mozilla-services/heka && \
    source build.sh && \
    mkdir /usr/share/heka && \
    cp -r /go/src/github.com/mozilla-services/heka/build/heka/* /usr/share/heka/ && \
    go clean -i -r && \
    apk del --purge build-base go git mercurial cmake perl && \
    rm -rf ${GOPATH} /tmp/* /var/cache/apk/* /root/.n*

RUN for i in decoders encoders filters modules; do \
		mkdir -p /usr/share/heka/lua_${i} && \
	cp /go/src/github.com/mozilla-services/heka/sandbox/lua/${i}/* /usr/share/heka/lua_${i}; \
	done && \
	cp /go/src/github.com/mozilla-services/heka/sandbox/lua/modules/* /usr/share/heka/lua_modules && \
	cp -r /go/src/github.com/mozilla-services/heka/dasher /usr/share/heka/ && \
        mkdir /etc/heka

COPY *.toml /etc/heka/

VOLUME /var/run/docker.sock


ENTRYPOINT ["/usr/bin/hekad", "-c", "/etc/heka/"]
